# Generated by Django 5.1.2 on 2024-10-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_emailmessage_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailmessage",
            name="received_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="sent_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
